### ISSUE TITLE
Duplicate sent_id

### ISSUE THREAD

**Issue by xrotwang** [UniversalDependencies/UD_Kaapor-TuDeT#1]
Here
https://github.com/UniversalDependencies/UD_Kaapor-TuDeT/blob/0578be9f33b8c0b981b4f5686ca0673c30244dbe/urb_tudet-ud-test.conllu#L150
and here
https://github.com/UniversalDependencies/UD_Kaapor-TuDeT/blob/0578be9f33b8c0b981b4f5686ca0673c30244dbe/urb_tudet-ud-test.conllu#L298

**Comment by xrotwang** [comment]
@LanguageStructure can you fix this, so we can have a consistent tudet release?

**Comment by LanguageStructure** [comment]
sure! I will fix it now
